#!/usr/bin/sh

#check for key arguement
if [ -z $1 ]; then
	echo "Usage $0 <API Key>"
	exit -1
fi

API_KEY=$1
INSTALL_DIR=`xdg-user-dir DOCUMENTS`/Anki/addons

#copy plugin files
cp forvo-dl.py $INSTALL_DIR
cp -r forvo $INSTALL_DIR
 
#link to requests library
cd $INSTALL_DIR/forvo
REQUESTS_DIR=`pip show requests | grep Location | sed 's/^.* \(.*$\)/\1/'`
ln -sf $REQUESTS_DIR/requests

echo $API_KEY > ~/.forvo

